### PR TITLE
"up7c" -> "up7d"

### PR DESCRIPTION
**Pull request by thiswillbeyourgithub**
:)

### CODE REVIEW

**Comment by bfontaine** [comment]
Thank you! Does the script still work? I haven’t used it since ~ 2013.

**Comment by thiswillbeyourgithub** [comment]
It's sort of hit and miss. I have definitely seen it working and sometimes I have weird errors. I am not familiar with ruby though so I'll have to sit on it :)

Definitely is a help sometimes so thanks for charing :)

PS : I had to change line #74 because my laptop doesn't use wlan0

**Comment by thiswillbeyourgithub** [comment]
By any chance, is there a way this package could be used to connect to "Paris Wifi" ? It just needs to enter any mail adress.

**Comment by bfontaine** [comment]
What’s "Paris Wifi"?

**Comment by thiswillbeyourgithub** [comment]
The new Hotspots that are everywhere in Paris, in most parks and public library

**Comment by bfontaine** [comment]
Well I guess you can try to adapt the code for it 😃

**Comment by thiswillbeyourgithub** [comment]
Maybe one day ^^

**Pull request merged**
